name: Deploy

on:
  workflow_call:
    inputs:
      java-version:
        required: false
        type: string
      app-name:
        required: true
        type: string
      extra-json-file:
        required: false
        default: false
        type: boolean
      env-vars:
        required: false
        type: string
    secrets:
      extra-json-file-name:
        required: false
      extra-json-file-content:
        required: false
      extra-json-file-dir:
        required: false
      host:
        required: true
      username:
        required: true
      key:
        required: true
      passphrase:
        required: true
      

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4.2.2

      - name: Install Java
        uses: actions/setup-java@v4.6.0
        with:
          distribution: 'temurin'
          java-version: ${{ inputs.java-version }}

      # Used only by tracker for gdrive_credentials.json
      # Will be removed in the future
      - name: Create extra file
        uses: jsdaniell/create-json@v1.2.3
        if: ${{ inputs.extra-json-file }}
        with:
          name: ${{ secrets.extra-json-file-name }}
          json: ${{ secrets.extra-json-file-content }}
          dir: ${{ secrets.extra-json-file-dir }}

      - name: Package
        run: |
          # TODO: is this needed?
          #sed -i 's+./logs/+${HOME}/logs/+g' src/main/resources/logback-spring.xml

          IFS=$'\n'
          for line in ${{ inputs.env-vars }}
          do 
            declare -x "$line"
          done

          mvn -q clean package

      - name: Copy deploy script to target
        run: cp deploy.sh target/

      - name: Stop project if running
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.host }}
          username: ${{ secrets.username }}
          key: ${{ secrets.key }}
          passphrase: ${{ secrets.passphrase }}
          script: |
            cd $HOME
            if [ -f deploy.sh ]; then
              ./deploy.sh -n ${{ inputs.app-name }} -a stop
            else
              echo Unable to find deploy script, skip stopping
            fi
            rm -rf apps/${{ inputs.app-name }}

      - name: Copy project files
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.host }}
          username: ${{ secrets.username }}
          key: ${{ secrets.sshkey }}
          passphrase: ${{ secrets.passphrase }}
          source: "target/deploy.sh, target/${{ inputs.app-name }}.jar"
          target: "$HOME/apps/${{ inputs.app-name }}"
          strip_components: 1

      - name: Run project
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.host }}
          username: ${{ secrets.username }}
          key: ${{ secrets.sshkey }}
          passphrase: ${{ secrets.passphrase }}
          script: |
            IFS=$'\n'
            for line in ${{ inputs.env-vars }}
            do 
              declare -x "$line"
            done

            cd $HOME
            chmod +x deploy.sh
            ./deploy.sh -n ${{ inputs.app-name }} -a start