name: Deploy

on:
  workflow_call:
    inputs:
      app-name:
        required: true
        type: string
    secrets:
      host:
        required: true
      username:
        required: true
      key:
        required: true
      passphrase:
        required: true
      

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Download application jar
        uses: actions/download-artifact@v4
        with:
          name: application   
      
      - name: ls test
        run: |
          ls -l

      - name: Stop project if running
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.host }}
          username: ${{ secrets.username }}
          key: ${{ secrets.key }}
          passphrase: ${{ secrets.passphrase }}
          script: |
            ./deploy.sh -n ${{ inputs.app-name }} -a stop
            rm -rf apps/${{ inputs.app-name }}

      - name: Copy project files
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.host }}
          username: ${{ secrets.username }}
          key: ${{ secrets.key }}
          passphrase: ${{ secrets.passphrase }}
          source: "${{ inputs.app-name }}.jar"
          #target: "apps/${{ inputs.app-name }}/"
          strip_components: 1

      - name: Run project
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.host }}
          username: ${{ secrets.username }}
          key: ${{ secrets.key }}
          passphrase: ${{ secrets.passphrase }}
          script: |
            ./deploy.sh -n ${{ inputs.app-name }} -a start