name: Deploy

on:
  workflow_call:
    inputs:
      app-name:
        required: true
        type: string
    secrets:
      host:
        required: true
      username:
        required: true
      key:
        required: true
      passphrase:
        required: true
      

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Download application jar
        uses: actions/download-artifact@v4
        with:
          name: application
          path: 'target/'

      - name: Copy deploy script to target
        run: cp deploy.sh target/

      - name: Stop project if running
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.host }}
          username: ${{ secrets.username }}
          key: ${{ secrets.key }}
          passphrase: ${{ secrets.passphrase }}
          script: |
            cd $HOME
            if [ -f deploy.sh ]; then
              ./deploy.sh -n ${{ inputs.app-name }} -a stop
            else
              echo Unable to find deploy script, skip stopping
            fi
            rm -rf apps/${{ inputs.app-name }}

      - name: Copy project files
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.host }}
          username: ${{ secrets.username }}
          key: ${{ secrets.sshkey }}
          passphrase: ${{ secrets.passphrase }}
          source: "target/deploy.sh, target/${{ inputs.app-name }}.jar"
          target: "$HOME/apps/${{ inputs.app-name }}"
          strip_components: 1

      - name: Run project
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.host }}
          username: ${{ secrets.username }}
          key: ${{ secrets.sshkey }}
          passphrase: ${{ secrets.passphrase }}
          script: |
            cd $HOME
            chmod +x deploy.sh
            ./deploy.sh -n ${{ inputs.app-name }} -a start